$terminal = kitty
$fileManager = thunar
$menu = rofi -modi run,drun -show drun -show-icons -display-run "Launch" -display-drun "Launch"

$browser = firefox
$locker = hyprlock

bind = $mainMod, Return, exec, $terminal
bind = $mainMod SHIFT, E, exec, uwsm stop
bind = $mainMod SHIFT, X, exec, $locker
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, Space, exec, $menu
bind = , Menu, exec, $menu
bind = $mainMod, Q, killactive,
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -

bind = $mainMod, X, exec, kitty --class clipse clipse
# bind = $mainMod, X, setfloating
# bind = $mainMod, X, centerwindow
