bind = $mainMod SHIFT, M, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0

bind = $mainMod CTRL, Space, togglefloating
bindr = $mainMod CTRL, Control_L, submap, floating

submap = floating
bind = , Space, togglefloating
bind = , Return, pin
bind = , C, centerwindow
bind = , catchall, exec, :
bind = , Escape, submap, reset
submap = reset

bind = $mainMod CTRL, R, submap, resize

submap = resize
binde = , right, resizeactive, 10 0
binde = , left, resizeactive, -10 0
binde = , up, resizeactive, 0 -10
binde = , down, resizeactive, 0 10
bind = , catchall, exec, :
bind = , escape, submap, reset
submap = reset

bind = $mainMod CTRL, C, layoutmsg, movetoroot
