$mainMod = SUPER

source = ~/.config/hypr/keybinds/workspace.conf
source = ~/.config/hypr/keybinds/focus.conf
source = ~/.config/hypr/keybinds/apps.conf
source = ~/.config/hypr/keybinds/layout.conf
source = ~/.config/hypr/keybinds/media.conf
source = ~/.config/hypr/keybinds/notifications.conf

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

